apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirector-deployment
  labels:
    app: redirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirector
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: apache
        image: quay.io/jkeam/redirector-apache@sha256:4ebf44294816fbc97d233cca1a9fdecab5068993881540eeb4cb59744ec83c0e
        ports:
        - containerPort: 8000
      - name: springboot
        image: quay.io/jkeam/redirector@sha256:70b1538ef86080b951d694a452c5d4e15e1d38de8458028d60a9dd5d4378e0cb
        ports:
        - containerPort: 8081
