apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirector-deployment
  labels:
    app: redirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirector
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: apache
        image: quay.io/jkeam/redirector-apache@sha256:9a0efc1d483856d39e051a00e7ef186f51e905214c0898de0a3bea7ac82912fa
        ports:
        - containerPort: 8000
        - containerPort: 7000
      - name: springboot
        image: quay.io/jkeam/redirector@sha256:74090cbe4c6da78e66d2e336b279d144c9e3a2d669c8f0e22749b6bb5948e3d7
        ports:
        - containerPort: 8081
